name: Portfolio CI

on:
  push:
    branches:
      - master

jobs:
  prepare:
    name: Portfolio Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Project
        run: |
          npm i -g @angular/cli
          npm install
          ng build
      - name: List output files
        run: find dist/mywebsite/ -print

      - name: Upload Build
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/mywebsite/
